<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="scara">
<!--<xacro:property name="cyl_radius" value="0.2" />-->
<!--<xacro:property name="cyl_length" value="0.6" />-->
<!--<xacro:property name="rect_length" value="2" />-->
<!--<xacro:property name="rect_height" value="0.2" />-->
<!--<xacro:property name="rect_width" value="0.3" />-->
<!--<xacro:property name="cyl2_length" value="0.3" />-->
<!--<xacro:property name="ee_radius" value="0.05" />-->
<xacro:property name="cyl_radius" value="0.3" />
<xacro:property name="cyl_length" value="0.6" />
<xacro:property name="rect_length" value="2" />
<xacro:property name="rect_height" value="0.2" />
<xacro:property name="rect_width" value="0.3" />
<xacro:property name="cyl2_length" value="0.3" />
<xacro:property name="ee_radius" value="0.05" />


<!--    Materials-->
<material name = 'blue'>
    <color rgba="0 0.8 0.8 0.8"/>
</material>

<material name = 'yellow'>
    <color rgba="1 1 0 0.8"/>
</material>

<material name = 'pink'>
    <color rgba="1 0.4 0.7 0.8"/>
</material>

<material name = 'green'>
    <color rgba="0 1 0 0.8"/>
</material>


<!--Base link -->
<link name="base_link">
    <visual>
        <origin xyz="0 0 ${cyl_length/2}"/>
        <geometry>
            <cylinder length="${cyl_length}" radius="${cyl_radius}"/>
        </geometry>
        <material name = 'yellow'/>
    </visual>
</link>

<joint name="base_link_to_link1" type="continuous">
    <parent link="base_link"/>
    <child link="link1"/>
    <axis xyz="0 0 1"/>
    <origin xyz="0 0 ${cyl_length + cyl2_length/2 - rect_height/2}"/>
</joint>

<!--Link 1-->
<link name="link1">
    <visual>
        <origin xyz="${rect_length/2} 0 ${rect_height/2}"/>
        <geometry>
            <box size = "${rect_length} ${rect_width} ${rect_height}" />
        </geometry>
        <material name = 'blue'/>
    </visual>
</link>

<link name="link1_visual">
    <visual>
        <origin xyz="0 0 ${cyl2_length/2}"/>
        <geometry>
            <cylinder length="${cyl2_length}" radius="${cyl_radius}" />
        </geometry>
        <material name = 'blue'/>
    </visual>
</link>

<joint name="link1_to_link1_visual" type="fixed">
    <parent link="link1"/>
    <child link="link1_visual"/>
    <origin xyz="0 0 ${-cyl2_length/2 + rect_height/2}"/>
</joint>


<joint name="link1_to_link2" type="continuous">
    <parent link="link1"/>
    <child link="link2"/>
    <axis xyz="0 0 1"/>
    <origin xyz="${rect_length} 0 0"/>
</joint>

<!--Link 2-->
<link name="link2">
    <visual>
        <origin xyz="${rect_length/2} 0 ${rect_height/2}"/>
        <geometry>
            <box size = "${rect_length} ${rect_width} ${rect_height}" />
        </geometry>
        <material name = 'pink'/>
    </visual>
</link>

<link name="link2_visual">
    <visual>
        <origin xyz="0 0 ${cyl2_length/2}"/>
        <geometry>
            <cylinder length="${cyl2_length}" radius="${cyl_radius}" />
        </geometry>
        <material name = 'pink'/>
    </visual>
</link>

<joint name="link2_to_link2_visual" type="fixed">
    <parent link="link2"/>
    <child link="link2_visual"/>
    <origin xyz="0 0 ${-cyl2_length/2 + rect_height/2}"/>
</joint>

<joint name="link2_to_ee_link" type="prismatic">
    <parent link="link2"/>
    <child link="ee_link"/>
    <limit effort="1000.0" lower="0" upper="0.6" velocity="0.5"/>
    <axis xyz="0 0 1"/>
    <origin xyz="${rect_length} 0 0"/>
</joint>

<!--    Ee_link-->
<link name="ee_link">
    <visual>
        <origin xyz="0 0 -${cyl_length/2}"/>
        <geometry>
            <cylinder length="${cyl_length}" radius="${ee_radius}" />
        </geometry>
        <material name = 'green'/>
    </visual>
</link>

<link name="ee_link_visual">
    <visual>
        <origin xyz="0 0 ${cyl2_length - rect_height}"/>
        <geometry>
            <cylinder length="${cyl2_length}" radius="${cyl_radius}" />
        </geometry>
        <material name = 'pink'/>
    </visual>
</link>

<joint name="link2_to_ee_link_visual" type="fixed">
    <parent link="link2"/>
    <child link="ee_link_visual"/>
    <origin xyz="${rect_length} 0 0"/>
</joint>


</robot>
